### ISSUE TITLE
Use of pycutest with virtual environments

### ISSUE THREAD

**Issue by payoto** [jfowkes/pycutest#12]
A very nice package for using CUTEst, thanks a lot for the work.

## Issue

I can get the package to work, but I find the ${PYCUTEST_CACHE} environment variable a pain point
when working with multiple environments that use pycutest. It makes sense that this would be separate as you might want to manage a global CUTEst function cache but having to manually add it to the python path is a pain, especially when trying to replicate an install on someone else's computer.

## Proposed solution(s)

* Add a fallback if the environment variable is not defined in the `sites-packages/pycutest/` folder.
* Add the ${PYCUTEST_CACHE} environment variable to the python path when `pycutest` is imported. 

These changes seem to superficially have the benefit of being backwards compatible.

I'm happy to do a PR with either or both of those things if you're interested but thought I'd bring it up first.

**Comment by jfowkes** [comment]
Thank you very much! 

Regarding your issue, we do actually have a fallback in that PyCUTEst will default to using the current working directory to store the cache if the ${PYCUTEST_CACHE} environment variable is not defined (see the end of `system_paths.py`), although I realise that we have probably not documented this anywhere and we should really make this behaviour clear in the README and documentation.

**Comment by payoto** [comment]
I see that default now, good to know! I'll have a bit of time in the next couple of weeks where I can probably document that and PR it.

What would you think of `pycutest` adding the contents of the `${PYCUTEST_CACHE}` variable to the python path automatically? (or at least providing a function to do it automatically). Would you be interested in a PR doing that?

**Comment by jfowkes** [comment]
No worries, a documentation PR for the default cache handling would be much appreciated, many thanks!

Regarding `pycutest` automatically adding the contents of `${PYCUTEST_CACHE}` to the python path, I will have to ask my co-author who wrote the environment variable handling code. @lindonroberts do you think this would be a good idea?

**Comment by lindonroberts** [comment]
I think adding PYCUTEST_CACHE to the Python path automatically would be a nice feature. This would simplify the installation a little bit too (only needing to set PYCUTEST_CACHE and not PYTHONPATH). Happy for a PR on this

**Comment by lindonroberts** [comment]
Because I had to deal with this today, a code snippet I needed to update the Python path at runtime to include PYCUTEST_CACHE:

```
import os, sys
try:
    sys.path.index(os.environ['PYCUTEST_CACHE'])
except ValueError:
    sys.path.append(os.environ['PYCUTEST_CACHE'])
```

In our case it would be similar, but with `get_cache_path()` instead of `os.environ['PYCUTEST_CACHE']`, so

```
import sys
try:
    sys.path.index(get_cache_path())
except ValueError:
    sys.path.append(get_cache_path())
```

It would make sense for this to go at the end of `__init__.py`, since that also does things like check existence of environment variables.

**Comment by jfowkes** [comment]
Sounds good to me, would be great to have this feature if you're able to add it?

**Comment by lindonroberts** [comment]
Reopening as a reminder to mention the "if environment variable not available use the current directory" behavior in the documentation

**Comment by jfowkes** [comment]
Many thanks! I guess we should probably think about a new release with updated docs soon?

**Comment by lindonroberts** [comment]
I agree - to this end in commit f0b5427ed6cddb2cc4a19a6e4c412eb9a0b529a1 I have updated:

- Increased version number to 1.1
- Documentation to include simplified installation (remove any reference to updating PYTHONPATH), updated version history. I set the release date to 14 Feb to give @jfowkes time to check things over
- Misc documentation changes: updated index.rst to use my homepage rather than (old) email, updated link for Windows/WSL info

**Comment by jfowkes** [comment]
Fantastic, thank you very much @lindonroberts for this addition and for the comprehensive docs update. This looks great to me, please release the new release!

**Comment by lindonroberts** [comment]
@jfowkes - I've tagged release v1.1 and made it available on pyPI (https://pypi.org/project/pycutest/)
