### ISSUE TITLE
SIFDECODE failed

### ISSUE THREAD

**Issue by melodyqxuan** [jfowkes/pycutest#13]
Hi,

I was able to install the pycutest on my Mac and import it in python. However, when I try to run:
 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycutest
>>> p=pycutest.import_problem("ROSENBR")"

it returned the following:

=========================================================================================
dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib
  Referenced from: /usr/local/opt/sifdecode/libexec/objects/mac64.osx.gfo/double/run_sifdecode
  Reason: image not found
/usr/local/opt/sifdecode/libexec/bin/sifdecoder: line 451:  2582 Abort trap: 6           $DECODER

 ERROR: Error exit from decoding stage. terminating execution.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/melody/anaconda3/lib/python3.6/site-packages/pycutest/build_interface.py", line 340, in import_problem
    objList = decode_and_compile_problem(problemName, destination, sifParams, sifOptions, quiet)
  File "/Users/melody/anaconda3/lib/python3.6/site-packages/pycutest/build_interface.py", line 215, in decode_and_compile_problem
    raise RuntimeError('SIFDECODE failed, check output printed above')
RuntimeError: SIFDECODE failed, check output printed above
=========================================================================================
I'm wondering if you can help me with this issue. Many thanks!

**Comment by jfowkes** [comment]
Hi, this is an issue with CUTEst on Mac (specifically SIFDecode) not being able to find GCC 9, most likely because you have updated GCC to a newer version since installing CUTEst. Please reinstall CUTEst and test SIFDecode:
```
brew reinstall cutest --without-single
brew test sifdecode
```

**Comment by melodyqxuan** [comment]
Thanks for your reply! I tried to reinstall but the test failed and returned the following:

$ brew test sifdecode
Testing optimizers/cutest/sifdecode
==> /usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder /usr/local/opt/sifdecode/li
Last 15 lines from /Users/melody/Library/Logs/Homebrew/sifdecode/test.01.sifdecoder:
2020-07-31 13:01:02 -0500

/usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder
/usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF

dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/9/libgfortran.5.dylib
  Referenced from: /usr/local/opt/sifdecode/libexec/objects/mac64.osx.gfo/double/run_sifdecode
  Reason: image not found
/usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder: line 451:  7266 Abort trap: 6           $DECODER

 ERROR: Error exit from decoding stage. terminating execution.

Error: optimizers/cutest/sifdecode: failed
An exception occurred within a child process:
  BuildError: Failed executing: /usr/local/Cellar/sifdecode/2.0.1/bin/sifdecoder /usr/local/opt/sifdecode/libexec/sif/ROSENBR.SIF
/usr/local/Homebrew/Library/Homebrew/formula.rb:2010:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1948:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1948:in `system'
/usr/local/Homebrew/Library/Taps/optimizers/homebrew-cutest/sifdecode.rb:77:in `block (2 levels) in <class:Sifdecode>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `chdir'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/fileutils.rb:128:in `cd'
/usr/local/Homebrew/Library/Taps/optimizers/homebrew-cutest/sifdecode.rb:76:in `block in <class:Sifdecode>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1818:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1817:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:900:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1816:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2060:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2059:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1810:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:35:in `block in <main>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:34:in `<main>'

**Comment by jfowkes** [comment]
Thank you for testing, could you please create a new issue upstream at https://github.com/optimizers/homebrew-cutest
It is an issue with their SIFDecode and they should be able to help you resolve it.

**Comment by melodyqxuan** [comment]
Thanks for your help!

**Comment by melodyqxuan** [comment]
I actually tried to reinstall SIFDecode and I was able to pass the test for sifdecode. However, I encountered a new issue when I try to import the problem:

>>> p = pycutest.import_problem('ROSENBR')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/melody/anaconda3/lib/python3.6/site-packages/pycutest/build_interface.py", line 357, in import_problem
    raise error
  File "/Users/melody/anaconda3/lib/python3.6/site-packages/pycutest/build_interface.py", line 349, in import_problem
    return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
ModuleNotFoundError: No module named 'pycutest_cache_holder.ROSENBR'

**Comment by melodyqxuan** [comment]
Hi,

Hi! I was able to fix the issue above, but encountered another issue. 

>>> pycutest.import_problem("ROSENBR")
Segmentation fault: 11

I was able to pinpoint the source of segmentation error to function calls to pycutestitf.cpython-36m-darwin.so made in _init__.py. In particular, while calling either

 > (n, m)=_pycutestitf._dims()

or

> info=_pycutestitf._setup(efirst, lfirst, nvfirst)

segmentation error will occur. Thanks in advance for your help!

**Comment by jfowkes** [comment]
> I actually tried to reinstall SIFDecode and I was able to pass the test for sifdecode.

Ah sorry, yes I forgot sifdecode is installed as a separate hombrew package. Glad you got it working!

> Hi! I was able to fix the issue above, but encountered another issue.
> 
> > > > pycutest.import_problem("ROSENBR")
> > > > Segmentation fault: 11
> 
This is a known issue when using Anaconda, please see the end of the discussion of PyCUTEst Issue #9 (Segmentation Fault 11). Basically Anaconda targets a very old version of MacOS when compiling and you need to tell it to target your current MacOS version (which should be the default but Anaconda developers don't want to change this). You can do this by setting `export MACOSX_DEPLOYMENT_TARGET=10.14` (or whatever your current MacOS version is, 10.14=Mojave, 10.15=Catalina, etc) in the terminal before running Anaconda python. You may need to create a new python environment using conda where only PyCUTEst is installed in order for it to work, see the end of the detailed discussion in PyCUTEst Issue #9.

**Comment by melodyqxuan** [comment]
Unfortunately, even after setting the target version and a new environment, I'm still getting the segmentation error...

**Comment by jfowkes** [comment]
I see, in that case my only suggestion would be to use homebrew python (`brew install python`) instead of Anaconda.

**Comment by melodyqxuan** [comment]
Thanks:)
