### ISSUE TITLE
When I am compiling any c++ program i am getting this error.Please tell me how to remove this. 

### ISSUE THREAD

**Issue by Sanchit1041** [jfowkes/pycutest#15]
ld: warning: dylib (/opt/homebrew/Cellar/gcc/10.2.0_4/lib/gcc/10/libstdc++.dylib) was built for newer macOS version (11.2) than being linked (11.0)

**Comment by jfowkes** [comment]
This is an issue with homebrew (not PyCUTEst): please apply the latest software updates to your mac (you have version 11.0 but two sets of patches have already been released for Big Sur)
