### ISSUE TITLE
Potential issue with problem import and objective function call

### ISSUE THREAD

**Issue by TangYihe** [jfowkes/pycutest#16]
Hello! 

First I would sincerely thank you for developing such a great interface, however, while using pyCUTEst, I noticed some issue related to problem import and objective function call for some problem instances. 

Namely, problems `'WAYSEA1NE'` and `'HIMMELBA'` triggers `AttributeError: module 'pycutest_cache_holder.WAYSEA1NE' has no attribute 'info'` when I import them via `pycutest.import_problem()`.

Also, for some problems, the function value and gradient are evaluated to `0.0, array([0.0, 0.0])`, respectively, at the initial point for that problem, via calling `problem.obj(problem.x0, gradient=True)`. I also tried obtaining the function value for a few points close to the initial point, which also gives the function value and gradient being all 0. I'm wondering if this is an issue related to my usage or the interface itself. 

Here's the list of problems with the issue mentioned above: `['BEALENE','BOXBOD','BROWNBSNE','CLUSTER', 'DANIWOOD','DANWOOD','DENSCHNCNE','ELATVIDUNE', 'EXPFITNE','FBRAIN','FBRAINNE','GBRAIN','GOTTFR', 'HIMMELBC','HIMMELBD','HS1NE','HS8','HYPCIR', 'JENSMPNE','JUDGENE','MISRA1A','MISRA1B','MISRA1C', 'MISRA1D','POWELLBS','POWELLSQ','PRICE3NE', 'PRICE4NE','RSNBRNE','S308NE','SINVALNE','WAYSEA2NE']`

I attached a pdf file illustrating the two issues I mentioned above. 

I sincerely appreciate your time taking a look into my issue.

Best wishes,
Yihe 
[pyCUTEst issue.pdf](https://github.com/jfowkes/pycutest/files/7466004/pyCUTEst.issue.pdf)

**Comment by jfowkes** [comment]
Hello, thank you very much for reporting this! With regards to your first issue, I'm unable to reproduce this:
```
~ $ python
Python 3.9.7 (default, Oct 22 2021, 09:16:56) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycutest as pct
>>> pct.import_problem('WAYSEA1NE')
<pycutest.problem_class.CUTEstProblem object at 0x7f517f1b4340>
>>> pct.import_problem('HIMMELBA')
<pycutest.problem_class.CUTEstProblem object at 0x7f517f15fc10>
``` 
Please could you clear out your `PYCUTEST_CACHE` folder? Also please ensure that you have set a `PYCUTEST_CACHE` folder and it is on your python path as per the docs, e.g. in my `~/.bashrc` I have:
```bash
export PYCUTEST_CACHE=/home/jari/Code/cutest/cache/
export PYTHONPATH="${PYCUTEST_CACHE}:${PYTHONPATH}"
```
The other thing to check is that the `WAYSEA1NE.SIF` and `HIMMELBA.SIF` problem definition files found in your mastsif folder are not corrupted (please see https://bitbucket.org/optrove/sif/src/master/ for the latest versions).

Regarding your second issue, you have discovered problems that are encoded as *Nonlinear Equations* (hence the NE in some of their names). Such problems have no objective function defined (as denoted by the N in their classification, see https://jfowkes.github.io/pycutest/_build/html/functions/pycutest.problem_properties.html). Instead their residual r(x) and Jacobian J(x) is accessed using `problem.cons()`. Typically you will want to use them as nonlinear least squares problems, in which case you can construct a standard objective function and gradient as (see e.g. Chapter 10 of Nocedal & Wright):
```
f(x) = 0.5*||r(x)||^2
g(x) = J(x)^T r(x)
```
however CUTEst does not do this for you unfortunately. Let me illustrate all this with a simple example:
```
~ $ python
Python 3.9.7 (default, Oct 22 2021, 09:16:56) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycutest as pct
>>> prob = pct.import_problem('BEALENE')
>>> pct.problem_properties('BEALENE')
{'objective': 'N', 'constraints': 'O', 'regular': True, 'degree': 2, 'origin': 'A', 'internal': False, 'n': 2, 'm': 3}
>>> prob.obj(prob.x0, gradient=True)
(0.0, array([0., 0.]))
>>> prob.cons(prob.x0, gradient=True)
(array([-1.5  , -2.25 , -2.625]), array([[ 0., -1.],
       [ 0., -2.],
       [ 0., -3.]]))
>>> 
```

**Comment by TangYihe** [comment]
Hello,

I fixed the first problem by clearing out the corresponding folders and re-import the problems. Thanks for the detailed explanation on the NE problems!

Many thanks for the timely response and again for implementing this interface!
