### ISSUE TITLE
Cannot make it work in Ubuntu 18.10 and Anaconda Python

### ISSUE THREAD

**Issue by pjssilva** [jfowkes/pycutest#2]
Hi,

I tried to installed it both using pip and manually but when trying to load any problem I get the error:

```python
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pycutest
>>> p = pycutest.import_problem('ROSENBR')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/continuum/anaconda3/lib/python3.7/site-packages/pycutest/build_interface.py", line 336, in import_problem
    return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
  File "/tmp/pycutestcache/pycutest_cache_holder/ROSENBR/__init__.py", line 63, in <module>
    (n, m)=_pycutestitf._dims()
Exception: Failed to open data file
```

If I go the the directory where the $PYCUTEST_CACHE/pycutest_cache_holder/ROSENBR directory and look for its contents I get:

```bash
AUTOMAT.d  build  cutestitf.c  ELFUN.f  ELFUN.o  EXTER.f  EXTER.o  GROUP.f  GROUP.o  __init__.py  OUTSDIF.d  __pycache__  PyCUTEst_automatic_test_function_interface_builder-1.0-py3.7.egg-info  _pycutestitf.cpython-37m-x86_64-linux-gnu.so  RANGE.f  RANGE.o  setup.py
```

**Comment by jfowkes** [comment]
Hi, that's because for some reason Anaconda thinks it's okay to append `.cpython-37m-x86_64-linux-gnu` to the end of the compiled extension (regular python does not do this).

As a quick fix you can rename `_pycutestitf.cpython-37m-x86_64-linux-gnu.so` to `_pycutestitf.so` while we investigate the root cause of this and find a way to resolve the issue.

@lindonroberts: any thoughts on this?

**Comment by pjssilva** [comment]
I tried, but no luck:
```python
Python 3.7.1 (default, Dec 14 2018, 19:28:38) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import pycutest                                                                                                                                                                                      
/opt/continuum/anaconda3/lib/python3.7/site-packages/pycutest/__init__.py:28: RuntimeWarning: the PYCUTEST_CACHE environment variable is not set; current folder will be used for caching.
  warnings.warn("the PYCUTEST_CACHE environment variable is not set; current folder will be used for caching.", RuntimeWarning)

In [2]: p = pycutest.import_problem("HS110")                                                                                                                                                                 
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-2-82d3da318ed4> in <module>
----> 1 p = pycutest.import_problem("HS110")

/opt/continuum/anaconda3/lib/python3.7/site-packages/pycutest/build_interface.py in import_problem(problemName, destination, sifParams, sifOptions, efirst, lfirst, nvfirst, quiet, drop_fixed_variables)
    334         problemDir = destination
    335     # Import the module CACHE_SUBFOLDER.problemDir, and return a wrapper
--> 336     return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
    337                          drop_fixed_variables=drop_fixed_variables)
    338 

~/documentos/pesquisa/splitLP/pycutest_cache_holder/HS110/__init__.py in <module>
     61 
     62 # Get problem dimension
---> 63 (n, m)=_pycutestitf._dims()
     64 
     65 # Set up the problem and get basic information

Exception: Failed to open data file

In [3]: 
```

**Comment by jfowkes** [comment]
Ok let's try debugging the exception: "Failed to open data file" means that `OUTSDIF.d` cannot be found or read, so the first thing to check is that `__init.py__` is looking for it in the correct place. Could you edit `HS110/__init.py__` after line 46 to print out `_directory` and `_module`?  

You should get something like `~/pycutest_cache_holder/HS110` for `_directory` and `_pycutestitf.cpython-37m-x86_64-linux-gnu.so` for `_module`.

**Comment by lindonroberts** [comment]
Hi, just to confirm, have you confirmed the underlying CUTEst install is working correctly? You can test with (from https://github.com/ralna/CUTEst/blob/master/doc/README):

```
cd $SIFDECODE/src ; make -f $SIFDECODE/makefiles/$MYARCH test
cd $CUTEST/src ; make -f $CUTEST/makefiles/$MYARCH test
```

**Comment by jfowkes** [comment]
Looks like a Fortran issue to me then: the "Failed to open data file" exception is thrown on line 115 of `c_interface.py` and indicates that the `FORTRAN_open` call on line 113 is failing for some reason. This could be due to incompatible Fortran compilers being used for CUTEst and PyCUTEst. At the moment we only support gfortran for PyCUTEst, are you using a different Fortran compiler for CUTEst itself?

**Comment by pjssilva** [comment]
I used gfortran 8.2 to compile CUTEst. Maybe some incompatibility between this gfortran version and the one Anaconda used? I will try today to install it using Ubuntu's Python and see how it goes.

**Comment by jfowkes** [comment]
Yes I suspect that's the issue: Anaconda uses gfortran 7.3 (as you can see from the first line of your initial code listing).

**Comment by jfowkes** [comment]
Did that fix your issue? I have updated the README with a note to ensure that PyCUTEst and CUTEst use the same version of gfortran.
