### ISSUE TITLE
Error in using pycutest

### ISSUE THREAD

**Issue by HanfengZeng** [jfowkes/pycutest#25]
Hi,

I follow the instruction in  https://jfowkes.github.io/pycutest/_build/html/install.html to install cutest on Mac.
My mac version is Monterey 12.5.  I use Pycharm with python 3.8 and gfortran 12.1

Then I run the tests in "Building Test Problem" of https://jfowkes.github.io/pycutest/_build/html/install.html
the first one "Find Problems", my output is fine
but the second one "Building Problems", my output is 

Parameters available for problem ARGLALE:
N = 10 (int) 
N = 50 (int) 
N = 100 (int) 
N = 200 (int) [default]
M = 20 (int, .ge. N) 
M = 100 (int, .ge. N) 
M = 200 (int, .ge. N) 
M = 400 (int, .ge. N) [default]
End of parameters for problem ARGLALE
Traceback (most recent call last):
  File "<input>", line 8, in <module>
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/cengzhe/Documents/pythonproject/test.py", line 53, in <module>
    problem = pycutest.import_problem('ARGLALE', sifParams={'N':100, 'M':200})
  File "/usr/local/anaconda3/envs/pythonProject/lib/python3.8/site-packages/pycutest/build_interface.py", line 348, in import_problem
    return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
  File "/usr/local/anaconda3/envs/pythonProject/lib/python3.8/site-packages/pycutest/problem_class.py", line 82, in __init__
    self.name = self._module.info['name']
AttributeError: module 'pycutest_cache_holder.ARGLALE_M200_N100' has no attribute 'info'

I check the  ''ARGLALE_M200_N100'  folder in 'pycutest_cache_holder' folder,  there is indeed no such 'info' file.  Why does this happen?  Looking forward to your reply!

**Comment by lindonroberts** [comment]
Hi, the attribute 'info' is defined as a variable in `pycutest_cache_holder/ARGLALE_M200_N100/__init__.py`. Do you have that file? For me, in `__init__.py` I see lines 65-66:
```
# Set up the problem and get basic information
info=_pycutestitf._setup(efirst, lfirst, nvfirst)
```
which is where the `info` attribute is defined. Do you see anything like this?

**Comment by HanfengZeng** [comment]
Thanks, I choose use linux and it works now!

**Comment by jfowkes** [comment]
This seems to be the exact same issue as #32 from another Anaconda user.
