### ISSUE TITLE
Hessian for constrained problems

### ISSUE THREAD

**Issue by lindonroberts** [jfowkes/pycutest#27]
As mentioned in the JOSS pull request: the error message when using hess (or sphess) and not passing in a Lagrange multiplier vector v for a constrained problem is not very friendly:
```
Traceback (most recent call last):
  File "/Users/jari/s_matrix.py", line 20, in <module>
    H = prob.sphess(x0)  # Sparse Hessian (COO)
  File "/usr/local/lib/python3.9/site-packages/pycutest/problem_class.py", line 667, in sphess
    self.check_input_v(v)
  File "/usr/local/lib/python3.9/site-packages/pycutest/problem_class.py", line 225, in check_input_v
    elif v.shape != (self.m,):
AttributeError: 'NoneType' object has no attribute 'shape'
```

My suggestion here is:

- For all problems, `prob.hess(x)`, `prob.ihess(x)`, `prob.sphess(x)` and `prob.isphess(x)` all return the Hessian of the objective
- For constrained problems, `prob.hess(x, v)` and `prob.sphess(x, v)` return the Hessian of the Lagrangian

@jfowkes - it seems that your instinct was that `hess(x)` returns the Hessian of the objective even for constrained problems, hence the issue.

**Comment by jfowkes** [comment]
@lindonroberts yes that was indeed my instinct, but I wonder if it makes sense to change the CUTEst default? Are there situations where one would want the Hessian of the objective for a constrained problem? And wouldn't this have side-effects on other CUTEst functions, namely the ones that return the gradient/Hessian of the Langrangian for constrained problems? I'm thinking of `gradhess` here in particular which also returns the Hessian of the objective for unconstrained problems and Hessian of the Lagrangian for constrained problems.

**Comment by lindonroberts** [comment]
That's a good point, and I agree with your reasoning. I guess we just need to have a check that `v is not None` for constrained problems.

**Comment by lindonroberts** [comment]
I've fixed this by just returning sensible AssertionError messages. For example:

```
>>> import pycutest
>>> prob = pycutest.import_problem("ALLINITC")
>>> prob.hess(prob.x0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/lindo/Documents/git/pycutest/pycutest/problem_class.py", line 461, in hess
    assert v is not None, "CUTEstProblem.hess: v must be specified for constrained problems. For the objective Hessian, use problem.ihess(x)"
AssertionError: CUTEstProblem.hess: v must be specified for constrained problems. For the objective Hessian, use problem.ihess(x)
>>> prob.sphess(prob.x0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/c/Users/lindo/Documents/git/pycutest/pycutest/problem_class.py", line 711, in sphess
    assert v is not None, "CUTEstProblem.sphess: v must be specified for constrained problems. For the objective Hessian, use problem.isphess(x)"
AssertionError: CUTEstProblem.sphess: v must be specified for constrained problems. For the objective Hessian, use problem.isphess(x)
```

Specifying `v` for unconstrained problems also returns an error message.
