### ISSUE TITLE
Clean up documentation

### ISSUE THREAD

**Issue by lindonroberts** [jfowkes/pycutest#3]
The main page with all the interface functions is hard to navigate - needs cleaning up (including links between list of available functions and definition, or entries on the LHS index sidebar, etc).

Needs some work because doc generation was automated with Sphinx autodoc extension (not sure how to modify). Alternatively, migrate everything into the rst files directly (not as nice, but at least it's fully configurable).

**Comment by jfowkes** [comment]
Agreed. At some point we should also push a new version to PyPI (especially as the latest versions of scipy/numpy drop python 2.7 support, see 29393ac).

**Comment by lindonroberts** [comment]
Looks great, thanks Jari!
