### ISSUE TITLE
Add citation information

### ISSUE THREAD

**Issue by lindonroberts** [jfowkes/pycutest#36]
**Is your feature request related to a problem? Please describe**
n/a

**Describe the solution you'd like**
We should add citation information to the README and documentation (beyond just the badge), to make it easy for everyone to see the citation info. 

(I'm quite busy with other things right now, so putting this here mostly as a reminder to myself!)

**Describe alternatives you've considered**
n/a

**Comment by jfowkes** [comment]
Agreed! I'm also quite busy atm but let's keep this as a reminder to ourselves.

**Comment by lindonroberts** [comment]
Added citation info to README in 8648f533662df68cbcbc003976c61e6916431a3d and front page of documentation (index.rst) in a05d7d3c1169cd5e9bb045c5822daf457979fe1d

**Comment by lindonroberts** [comment]
@jfowkes - I just realised we have CITATION.CFF which references Zenodo. What did you want to do with this? We could just replace the DOI with the JOSS one?

**Comment by jfowkes** [comment]
@lindonroberts good spot, yeah I guess we should change it to the JOSS DOI? The Zenodo was just a JOSS requirement and points to a specific archived version, but the JOSS paper itself also points to this so probably no point in having it in CITATION.CFF

**Comment by lindonroberts** [comment]
Sounds good - I've updated the DOI in [d061764](https://github.com/jfowkes/pycutest/commit/d061764862a4444938a6ff69940d4196d9d3f6ed)
