### ISSUE TITLE
Add access to gradient only

### ISSUE THREAD

**Issue by jeffrey-hokanson** [jfowkes/pycutest#40]
**Is your feature request related to a problem? Please describe**
Currently, the gradient for an unconstrained problem can only be accessed along with either the objective or Hessian:

```
_, g = prob.obj(x, gradient = True)
g, _ = prob.gradhess(x)
```
A similar issue is true with constrained problems.

**Describe the solution you'd like**
Ideally, I'd like to have access to the gradient alone, i.e.,
```
g = prob.grad(x)
```

**Describe alternatives you've considered**
This isn't a blocking change for my work since accessing the gradient through the objective is sufficiently cheap, but this approach is aesthetically unpleasing.

**Comment by jfowkes** [comment]
Thank you for the feature request, the lack of a direct function for accessing the gradient is not very user-friendly. We are just copying the CUTEst interfaces here, but I agree this would be desirable and relatively easy to do (essentially a wrapper around `problem.obj`).

@lindonroberts what are your thoughts on this?

**Comment by lindonroberts** [comment]
I agree this would be useful, and perhaps a similar interface to `problem.cons` to just extract constraint gradients. 

The only wrinkle I can see is that there is the internal CUTEst counter of objective/gradient/Hessian evaluations in `problem.report()` that would need adjusting. Perhaps a tally of how many times `problem.grad` is called, and subtract that from the total objective evaluations (since that information was ignored)?

**Comment by jeffrey-hokanson** [comment]
That's an interesting design choice in CUTEst, but I can see why it was made. Many (most? all?) optimization algorithms evaluate objective & gradient (e.g., steepest descent) or gradient & Hessian (e.g., Newton) at the same time. In the code I've been developing, I already extract the gradient as @jfowkes describes so this doesn't really bother me.

**Comment by jfowkes** [comment]
I have realised there is a `CUTEst_ugr` function for accessing the objective gradient only. I will add a PyCUTEst interface to this (and the equivalent function `CUTEst_ufn` for accessing the objective function only) in due course. Apologies for missing this.
