### ISSUE TITLE
path problem in mac

### ISSUE THREAD

**Issue by paulcon** [jfowkes/pycutest#45]
**Describe the bug**
The path returned on line 36 in system_paths.py using os.path.join is missing the "/" at the beginning of the string:
https://github.com/jfowkes/pycutest/blob/master/pycutest/system_paths.py#L36

**To Reproduce**
import pycutest

**Information about your installation:**
 - macOS 12.6.2, Xcode 13.4
 - Python 3.8, PyCharm 2022.3.1
 - PyCUTEst 1.4
 - CUTEst installed with homebrew
 - updated .bashrc

**Comment by jfowkes** [comment]
Thanks for reporting, the fallback path should not be hardcoded like this as this will break on the new ARM macs since they do not use '/usr/local/' by default (c.f. #39)

It should be done using:
```python
import subprocess
# extract the homebrew prefix 
homebrew_prefix = subprocess.check_output(['brew', '--prefix']).decode('utf-8')[:-1]

homebrew_path = os.path.join(homebrew_prefix, 'opt', 'cutest', 'lib', 'libcutest.a')
```
and similarly for all the other homebrew paths starting with `/usr/local/`.
