### ISSUE TITLE
Symbol not found: __intel_fast_memcpy

### ISSUE THREAD

**Issue by 531649773** [jfowkes/pycutest#5]
I tried to run the code "p = pycutest.import_problem('ROSENBR')", it raised an error:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-014005f54d1f> in <module>
----> 1 p = pycutest.import_problem('ROSENBR')

/anaconda3/lib/python3.7/site-packages/pycutest/build_interface.py in import_problem(problemName, destination, sifParams, sifOptions, efirst, lfirst, nvfirst, quiet, drop_fixed_variables)
    334         problemDir = destination
    335     # Import the module CACHE_SUBFOLDER.problemDir, and return a wrapper
--> 336     return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]),
    337                          drop_fixed_variables=drop_fixed_variables)
    338 

~/Documents/pycutest_cache/pycutest_cache_holder/ROSENBR/__init__.py in <module>
     37 from __future__ import absolute_import, division, print_function, unicode_literals
     38 
---> 39 from ._pycutestitf import *
     40 from . import _pycutestitf
     41 import os

ImportError: dlopen(/Users/ziyan/Documents/pycutest_cache/pycutest_cache_holder/ROSENBR/_pycutestitf.cpython-37m-darwin.so, 2): Symbol not found: __intel_fast_memcpy
  Referenced from: /Users/ziyan/Documents/pycutest_cache/pycutest_cache_holder/ROSENBR/_pycutestitf.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/ziyan/Documents/pycutest_cache/pycutest_cache_holder/ROSENBR/_pycutestitf.cpython-37m-darwin.so

It seems that there is something wrong with __intel_fast_memcpy. Does anyone know how to fix it? Thanks in advance.

**Comment by jfowkes** [comment]
I suspect that's because Anaconda has compiled the ROSENBR python extension using the Intel C compiler which is not supported. Please ensure that Anaconda is set to use GCC as the C compiler (this is the default), then clear the PyCUTEst cache and re-import ROSENBR.

**Comment by 531649773** [comment]
> I suspect that's because Anaconda has compiled the ROSENBR python extension using the Intel C compiler which is not supported. Please ensure that Anaconda is set to use GCC as the C compiler (this is the default), then clear the PyCUTEst cache and re-import ROSENBR.

Thanks for your reply. I forgot to mention that I was running the code on MacOS Mojave 10.14.5. I reinstalled the Anaconda , but the problem is not solved. I don't think the Intel C compiler is installed in my computer.  Below is the version of GCC in my computer:
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/c++/4.2.1
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by jfowkes** [comment]
Please can you do the following
```bash
cd ~/Documents/pycutest_cache/pycutest_cache_holder/ROSENBR/
rm -rf build/
DISTUTILS_DEBUG=1 python setup.py build
```
and post the output? This way we can see how the ROSENBR python extension is being compiled.

**Comment by 531649773** [comment]
> Please can you do the following
> 
> ```shell
> cd ~/Documents/pycutest_cache/pycutest_cache_holder/ROSENBR/
> rm -rf build/
> DISTUTILS_DEBUG=1 python setup.py build
> ```
> 
> and post the output? This way we can see how the ROSENBR python extension is being compiled.

It returns the following:

options (after parsing config files):
options (after parsing command line):
option dict for 'build' command:
  {}
running build
Distribution.get_command_obj(): creating 'build' command object
running build_ext
Distribution.get_command_obj(): creating 'build_ext' command object
building '_pycutestitf' extension
creating build
creating build/temp.macosx-10.7-x86_64-3.7
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ziyan/anaconda3/include -arch x86_64 -I/Users/ziyan/anaconda3/include -arch x86_64 -DLINUX -I/Users/ziyan/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy -I/Users/ziyan/anaconda3/include/python3.7m -c cutestitf.c -o build/temp.macosx-10.7-x86_64-3.7/cutestitf.o
creating build/lib.macosx-10.7-x86_64-3.7
gcc -bundle -undefined dynamic_lookup -L/Users/ziyan/anaconda3/lib -arch x86_64 -L/Users/ziyan/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/cutestitf.o RANGE.o EXTER.o ELFUN.o GROUP.o /Users/ziyan/Documents/Github/cutest/CUTEst/objects/mac64.osx.ifr/double/libcutest.a -L/usr/local/Cellar/gcc/9.1.0/lib/gcc/9/ -L/usr/local/gfortran/lib/ -lgfortran -o build/lib.macosx-10.7-x86_64-3.7/_pycutestitf.cpython-37m-darwin.so -Wl,-no_compact_unwind
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/'
ld: warning: object file (RANGE.o) was built for newer OSX version (10.14) than being linked (10.7)
ld: warning: object file (EXTER.o) was built for newer OSX version (10.14) than being linked (10.7)
ld: warning: object file (ELFUN.o) was built for newer OSX version (10.14) than being linked (10.7)
ld: warning: object file (GROUP.o) was built for newer OSX version (10.14) than being linked (10.7)

**Comment by jfowkes** [comment]
Ah it turns out that you have compiled CUTEst using the Intel Fortran compiler (as you have `mac64.osx.ifr/double/libcutest.a`) and this is not supported. 

Please reinstall CUTEst following the detailed instructions in the README for PyCUTEst, in particular please ensure that you select GNU gfortran as the fortran compiler.

**Comment by 531649773** [comment]
It works! Thanks!
