### ISSUE TITLE
PyCUTEst v1.5.0 breaks existing cached problems

### ISSUE THREAD

**Issue by jfowkes** [jfowkes/pycutest#50]
Regrettably PyCUTEst v1.5.0 breaks existing cached problems (we had to fix a memory leak).

When upgrading to PyCUTEst v1.5.0, please clear out your cache by deleting the $PYCUTEST_CACHE/pycutest_cache_holder directory:
```sh
rm -r $PYCUTEST_CACHE/pycutest_cache_holder/
```

Failure to do so will result in errors of the form:
```python
>>> pycutest.import_problem('ROSENBR')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jari/Code/pycutest/pycutest/build_interface.py", line 345, in import_problem
    return CUTEstProblem(importlib.import_module('%s.%s' % (CACHE_SUBFOLDER, problemDir)),
  File "/home/jari/Code/pycutest/pycutest/problem_class.py", line 52, in __new__
    module.info = module.setup() # setup CUTEst problem
AttributeError: module 'pycutest_cache_holder.ROSENBR' has no attribute 'setup'
```

**Comment by jfowkes** [comment]
@ragonneau just a heads up for a cache breaking change in the upcoming v1.5.0 release.

**Comment by ragonneau** [comment]
Great thanks for the reminder!

**Comment by KenZhenLin** [comment]
Hi, I sometimes get this error as well, and I fix it by deleting the folder you mention.

If I do not get this error,  does it mean everything works correctly? 

Or, I would have to clear out my cache each time I need to run the same code, even if there is no error?

Thanks!

**Comment by lindonroberts** [comment]
You only need to delete the cache once, when you install the new version (since your previous cache files would have been compiled under an older PyCUTEst version and are incompatible with PyCUTEst>=1.5).

**Comment by KenZhenLin** [comment]
> You only need to delete the cache once, when you install the new version (since your previous cache files would have been compiled under an older PyCUTEst version and are incompatible with PyCUTEst>=1.5).

Thanks for the fast response!

**Comment by KenZhenLin** [comment]
> You only need to delete the cache once, when you install the new version (since your previous cache files would have been compiled under an older PyCUTEst version and are incompatible with PyCUTEst>=1.5).

Although I should have mentioned, if this is helpful information: I think the only version I installed is PyCUTEst 1.5.0, so I had no trouble initially. But then I got this error in one of my running programs, and I was able to fix it by deleting that folder.

**Comment by KenZhenLin** [comment]
Hi, while I was trying to fix this error, I deleted my custom cache directory for my running program, but then I recreated that directory shortly. The program seems still be able to finish. Do you know if PyCUTEst created a new folder for cache when my custom directory was not there? I would like to delete the cache folder PyCUTEst if possible. Is there a way to print out the path to it? Also is it possible to print out the path to the default cache folder if I do not specify a custom one? I'm using Linux. Thanks!

**Comment by jfowkes** [comment]
@KenZhenLin PyCUTEst will automatically create a new cache subdirectory for each CUTEst problem when it is first imported, the location for this will be inside `$PYCUTEST_CACHE` if it has been set. For example, for problem `ROSENBR`, PyCUTEst will automatically create the directory
```
$PYCUTEST_CACHE/pycutest_cache_holder/ROSENBR/
```
If you do not specify a custom cache directory, then `pycutest_cache_holder` will be created in your current working directory. To locate all the cache directories you can simply search your system for directories with the name `pycutest_cache_holder`.

**Comment by KenZhenLin** [comment]
> @KenZhenLin PyCUTEst will automatically create a new cache subdirectory for each CUTEst problem when it is first imported, the location for this will be inside `$PYCUTEST_CACHE` if it has been set. For example, for problem `ROSENBR`, PyCUTEst will automatically create the directory
> 
> ```
> $PYCUTEST_CACHE/pycutest_cache_holder/ROSENBR/
> ```
> 
> If you do not specify a custom cache directory, then `pycutest_cache_holder` will be created in your current working directory. To locate all the cache directories you can simply search your system for directories with the name `pycutest_cache_holder`.

Thank you! I suppose if, by mistake, ```$PYCUTEST_CACHE``` has been set to a location that does not exist, PyCUTEst will give me an error message, instead of doing something else silently?

**Comment by jfowkes** [comment]
Closing as outdated due to new major release.
