### ISSUE TITLE
How to find problems with equality constraints only?

### ISSUE THREAD

**Issue by Xiaoyi-Qu** [jfowkes/pycutest#56]
Hi everyone, I am a new user to `pycutest` package. I used the function `probs = pycutest.find_problems(constraints='equality')` to find test problems with equality constraints only. I found 19 problems in total. However, as I typed the command `probs.m`, for all of them, the output is 0, which implies that all test problem I found have no constraints. I had no idea where I did wrong. Thank you for any suggestions.

**Comment by jfowkes** [comment]
Welcome @Xiaoyi-Qu, sorry we understand your confusion. What in PyCUTEst we currently call problems with only equality constraints correspond to problems whose only constraints are fixed variables, and by default PyCUTEst drops fixed variables when problems are imported (`drop_fixed_variables=True`).

For example, consider the `SSC` problem:
```bash
>>> prob = pycutest.import_problem('SSC')
>>> prob.n
4900
>>> prob.m
0
>>> prob = pycutest.import_problem('SSC', drop_fixed_variables=False)
>>> prob.n
5184
>>> prob.m
0
```

@lindonroberts perhaps the name `'equality'` is confusing/wrong here and should be `'fixed'` instead? Currently we are mapping SIF classification code X "the problem's only constraints are fixed variables" to `'equality'`.

**Comment by Xiaoyi-Qu** [comment]
Thank you very much for your clarification! If I understand correctly, to find test problems with equality constraints, I need to write a function myself.

**Comment by jfowkes** [comment]
@Xiaoyi-Qu yes that's correct unfortunately we don't currently have a way of finding problems with equality constraints.

**Comment by lindonroberts** [comment]
@jfowkes - yes, I hadn't thought about it, but `equality` is definitely confusing. I like your suggestion of `fixed` instead.

**Comment by jfowkes** [comment]
Thanks @lindonroberts, will change it to `fixed`, should probably also do a new minor release afterwards.
