### ISSUE TITLE
import_problem

### ISSUE THREAD

**Issue by yihang-gao** [jfowkes/pycutest#59]
Hi, when i use pycutest.import_prolem(), i get the following error:

 from ._pycutestitf import *
ImportError: dlopen(/Users/username/pycutest_cache/pycutest_cache_holder/BT9/_pycutestitf.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_cutest_cdh_'

May i ask how to solve it? Thanks very much!

**Comment by jfowkes** [comment]
Hello, I presume you are calling:
```
pycutest.import_problem('BT9')
```
Is that correct?

Are you on an M1 Mac or Intel Mac? Also are you using Anaconda Python, Homebrew Python or System Python?

Finally how was CUTEst installed? It looks like CUTEst might not be correctly installed as it provides `CUTEST_cdh`.

**Comment by yihang-gao** [comment]
> Hello, I presume you are calling:
> 
> ```
> pycutest.import_problem('BT9')
> ```
> 
> Is that correct?
> 
> Are you on an M1 Mac or Intel Mac? Also are you using Anaconda Python, Homebrew Python or System Python?
> 
> Finally how was CUTEst installed? It looks like CUTEst might not be correctly installed as it provides `CUTEST_cdh`.


Thanks for your reply. I'm using M1 Mac and system python. I installed CUTEst following the steps on the website... 
I try to install the cutest again:
$ brew install cutest
Warning: optimizers/cutest/cutest 2.0.2_2 is already installed and up-to-date.
To reinstall 2.0.2_2, run:
  brew reinstall cutest

**Comment by jfowkes** [comment]
Ah, anaconda support for compilation on M1 Macs is still very experimental (see #58 and related issues).

I would use pycutest with homebrew python instead:
```
brew install python@3.10
```
or whichever Python 3 version you desire (versions 3.8-3.11 are available).

More information on homebrew python is available here:
https://docs.brew.sh/Homebrew-and-Python

**Comment by yihang-gao** [comment]
> #58

Wow, thanks so much. Your reply greatly helps me!

**Comment by yihang-gao** [comment]
> Ah, anaconda support for compilation on M1 Macs is still very experimental (see #58 and related issues).
> 
> I would use pycutest with homebrew python instead:
> 
> ```
> brew install python@3.10
> ```
> 
> or whichever Python 3 version you desire (versions 3.8-3.11 are available).
> 
> More information on homebrew python is available here: https://docs.brew.sh/Homebrew-and-Python

Works well. Appreciate!
