### ISSUE TITLE
Check system path

### ISSUE THREAD

**Issue by lindonroberts** [jfowkes/pycutest#6]
In build_interface.import_problem(), check that cache is in the Python path. Easiest way would be to add an ImportError catch to lines 341-342:
`return CUTEstProblem(__import__('%s.%s' % (CACHE_SUBFOLDER, problemDir), globals(), locals(), [str(problemDir)]), drop_fixed_variables=drop_fixed_variables)`

If this throws an ImportError, just try to import CACHE_SUBFOLDER - an ImportError here indicates the Python path can't see it. This will hopefully avoid issues when using IDEs, etc.

**Comment by jfowkes** [comment]
This sounds like a sensible way of handling it to me.
