### ISSUE TITLE
Python Headers on Ubuntu

### ISSUE THREAD

**Issue by peterliu0104** [jfowkes/pycutest#79]
Hello, 

I'm using the Ubntu system. After I followed the instructions to install cutest and pycutest, it gives me the following error message. Any help would be greatly appreciated. 
![question](https://github.com/jfowkes/pycutest/assets/80781894/caace959-1e9e-4350-86bd-600eae3d8676)

**Comment by jfowkes** [comment]
Hello @peterliu0104, apologies it looks like Ubuntu doesn't install the required Python development headers by default. Please run 
```
sudo apt install python3.10-dev
```
to install the required Python header file. We will update the documentation to reflect this.

**Comment by peterliu0104** [comment]
@jfowkes Thanks so much for the help. It works! But it then says there is no attribute while I'm testing the problem. Should I update some packages? Thanks again for the help!
![question](https://github.com/jfowkes/pycutest/assets/80781894/4095dba8-69c4-4fc1-b86b-bc9e4d545ac2)

**Comment by jfowkes** [comment]
@peterliu0104 please delete the PyCUTEst Cache SubFolder and try again.
