### ISSUE TITLE
Error: could not convert string to float: '1.0D+5'

### ISSUE THREAD

**Issue by anugrahjo** [jfowkes/pycutest#91]
Hello,

When I run `pycutest.print_available_sif_params(prob_name)`, I get the following error for `prob_name` in `['FLOSP2HH', 'FLOSP2HL', 'FLOSP2HM', 'FLOSP2TH', 'FLOSP2TL', 'FLOSP2TM']`.

I use PyCUTEst 1.7.1 on macOS 14.4 with Python 3.9.13.
 
 ```
Parameters available for problem FLOSP2HH:
M = 1 (int, n=27) 
M = 2 (int, n=75) 
M = 5 (int, n=363 original value) 
M = 8 (int, n=867) 
M = 10 (int, n=1323) 
M = 15 (int, n=2883) [default]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/venv/lib/python3.9/site-packages/pycutest/sifdecode_extras.py", line 67, in print_available_sif_params
    value = float(value)
ValueError: could not convert string to float: '1.0D+7'
```

It's not a major issue for me. I just wanted to inform the developer team about this bug. 
Thanks.

**Comment by jfowkes** [comment]
@nimgould can we change `FLOSP2HH.SIF` to use `1.0E+7` for the Rayleigh number rather than the archaic `1.0D+7`?

@anugrahjo thank you for reporting, until this gets fixed  you can fix it yourself by editing `FLOSP2HH.SIF` to read:
```
*   Define the Rayleigh number. NB: This determines the difficulty 
*   of the problem.
  
 RE RA                  1.0E+7         $-PARAMETER Rayleigh number
```

**Comment by anugrahjo** [comment]
Thank you, @jfowkes . 

Just to be clear, even though I copied the error only for `'FLOSP2HH'`, it is applicable for all the six problems in `['FLOSP2HH', 'FLOSP2HL', 'FLOSP2HM', 'FLOSP2TH', 'FLOSP2TL', 'FLOSP2TM']`.

**Comment by jfowkes** [comment]
Thank you @nimgould I wasn't aware this was so prevalent as this is the only such error that I have seen.

@lindonroberts I suppose we should check if the string contains a `D` and replace it with `E` before passing it to `float()`? Or does Python have some built-in approach for handling this rather exotic Fortran exponential format? I believe this issue only affects `print_available_sif_params()` as in other cases the parameters are handled natively in Fortran.

**Comment by lindonroberts** [comment]
@jfowkes - after a bit of searching, I don't think Python has a built-in way to handling 'd'/'D' as an exponent. So, yes, I think it makes sense to do a find and replace for 'd'/'D' to 'e'

`value = float(value.replace('D','e').replace('d', 'e'))`

I'm not familiar enough with Fortran - are both 'd' and 'D' valid specifiers? I guess it can't hurt to allow both in our code

**Comment by jfowkes** [comment]
Thank you all, whilst this is no longer an issue for the current set of SIF problems, I think it makes sense to future proof the code against any future SIF files that do use D for the exponent since it is still valid Fortran. To this end, I have created a PR with the suggested find and replace fix in case this situation ever arises again. This can go into the next release.
